[package]
name = "red_book"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
red_book_libs = { path = "../red_book_libs"}
rand = "0.8.0"
rand_pcg = "0.3.1"